
// lib/firebase_options.dart

// This is a dummy file to allow the app to compile.
// It should be replaced with the real file generated by `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOI0ZYn_Eo5BfJ3Xdkyj0ZJVOwpM_hMgU',
    appId: '1:828734707901:web:d832d6824ca22a81853fd4',
    messagingSenderId: '828734707901',
    projectId: 'irrigration-9b71c',
    authDomain: 'irrigration-9b71c.firebaseapp.com',
    storageBucket: 'irrigration-9b71c.firebasestorage.app',
    measurementId: 'G-GXJ3DELRG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-nTySWTNpbSRjFTA7ardnMCTtuCVoGhI',
    appId: '1:828734707901:android:099b379e877ec500853fd4',
    messagingSenderId: '828734707901',
    projectId: 'irrigration-9b71c',
    storageBucket: 'irrigration-9b71c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy',
    appId: 'dummy',
    messagingSenderId: 'dummy',
    projectId: 'dummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dummy',
    appId: 'dummy',
    messagingSenderId: 'dummy',
    projectId: 'dummy',
  );
}